### ISSUE TITLE
Exception: Invalid "]" character in definition

### ISSUE THREAD

**Issue by jalanb** [kivy/pyjnius#120]
``` shell
$ git clone https://github.com/kivy/pyjnius.git
Cloning into 'pyjnius'...
remote: Counting objects: 878, done.
remote: Total 878 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (878/878), 209.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (515/515), done.
Checking connectivity... done.

$ cd pyjnius/

$ make tests
javac jnius/src/org/jnius/NativeInvocationHandler.java
python setup.py build_ext --inplace -f -g
```

yada, yada, all goes well until

``` shell
(test_method_multiple_signatures.MultipleSignature) ... ok
test_multiple_methods_varargs (test_method_multiple_signatures.MultipleSignature) ... ok
test_string_output_args (test_output_args.OutputArgs) ... ok
Failure: Exception (Invalid "]" character in definition "Landroid/bluetooth/BluetoothDevice;IB[])V") ... ERROR
test_stack (test_reflect.ReflectTest) ... ok
test_helloworld (test_simple.HelloWorldTest) ... ok

======================================================================
ERROR: Failure: Exception (Invalid "]" character in definition "Landroid/bluetooth/BluetoothDevice;IB[])V")
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alanb/.virtualenvs/bdr/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/alanb/.virtualenvs/bdr/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/alanb/.virtualenvs/bdr/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/alanb/tmp/pyjnius/tests/test_proxy.py", line 153, in <module>
    TestBadSignature()
  File "jnius_proxy.pxi", line 42, in jnius.PythonJavaClass.__init__ (jnius/jnius.c:22890)
  File "jnius_utils.pxi", line 32, in jnius.parse_definition (jnius/jnius.c:3832)
Exception: Invalid "]" character in definition "Landroid/bluetooth/BluetoothDevice;IB[])V"

----------------------------------------------------------------------
Ran 41 tests in 0.166s

FAILED (errors=1)
make: *** [tests] Error 1
```

From looking at the code this looks intentional (it is using a class called "TestBadSignature", but perhaps it should be wrapped into a test case ?
##

**Comment by KeyWeeUsr** [comment]
Ref #162, closed by #163.
