### ISSUE TITLE
OverflowError: Python int too large to convert to C long on ART

### ISSUE THREAD

**Issue by Davideddu** [kivy/pyjnius#146]
I'm getting this issue on Lollipop and I've been told it's a pyjnius bug by @kived.

This is the output of the accelerometer test application, it crashes when I enable the accelerometer.
```I/python  (15895):  Traceback (most recent call last):
I/python  (15895):    File "jnius/jnius_proxy.pxi", line 143, in jnius.jnius.py_invoke0 (jnius/jnius.c:25087)
I/python  (15895):    File "jnius/jnius_conversion.pxi", line 383, in jnius.jnius.convert_python_to_jobject (jnius/jnius.c:8842)
I/python  (15895):  OverflowError: Python int too large to convert to C long
W/System.err(15895): java.lang.NullPointerException: Expected to unbox a 'int' primitive type but was returned null
W/System.err(15895): 	at $Proxy0.hashCode(Unknown Source)
W/System.err(15895): 	at java.util.Collections.secondaryHash(Collections.java:3405)
W/System.err(15895): 	at java.util.HashMap.get(HashMap.java:300)
W/System.err(15895): 	at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:116)
W/System.err(15895): 	at android.hardware.SensorManager.registerListener(SensorManager.java:772)
W/System.err(15895): 	at android.hardware.SensorManager.registerListener(SensorManager.java:666)
W/System.err(15895): 	at org.renpy.android.SDLSurfaceView.nativeInit(Native Method)
W/System.err(15895): 	at org.renpy.android.SDLSurfaceView.run(SDLSurfaceView.java:726)
W/System.err(15895): 	at java.lang.Thread.run(Thread.java:818)
I/python  (15895): [INFO              ] [Base        ] Leaving application in progress...
I/python  (15895):  Traceback (most recent call last):
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/app/main.py", line 49, in <module>
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 792, in run
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 481, in runTouchApp
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 381, in mainloop
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 287, in _mainloop
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 324, in idle
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 309, in dispatch_input
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 220, in post_dispatch_input
I/python  (15895):    File "kivy/_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4690)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 648, in on_motion
I/python  (15895):    File "kivy/_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4690)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 660, in on_touch_down
I/python  (15895):    File "kivy/_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4690)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/widget.py", line 284, in on_touch_down
I/python  (15895):    File "kivy/_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4690)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/widget.py", line 284, in on_touch_down
I/python  (15895):    File "kivy/_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4690)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/widget.py", line 284, in on_touch_down
I/python  (15895):    File "kivy/_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4690)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/behaviors.py", line 93, in on_touch_down
I/python  (15895):    File "kivy/_event.pyx", line 312, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4636)
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1299, in custom_callback
I/python  (15895):    File "./accelerometertest.kv", line 30, in <module>
I/python  (15895):      on_press: root.do_toggle()
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/app/main.py", line 21, in do_toggle
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/facades.py", line 30, in enable
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/platforms/android/accelerometer.py", line 56, in _enable
I/python  (15895):    File "/home/ryan/git/kivy/tmp/acceltest/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/plyer/platforms/android/accelerometer.py", line 29, in enable
I/python  (15895):    File "jnius/jnius_export_class.pxi", line 830, in jnius.jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:22279)
I/python  (15895):    File "jnius/jnius_export_class.pxi", line 562, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:19029)
I/python  (15895):    File "jnius/jnius_export_class.pxi", line 656, in jnius.jnius.JavaMethod.call_method (jnius/jnius.c:20114)
I/python  (15895):    File "jnius/jnius_utils.pxi", line 43, in jnius.jnius.check_exception (jnius/jnius.c:3177)
I/python  (15895):  jnius.jnius.JavaException: JVM exception occured
I/python  (15895): Python for android ended.
I/art     (15895): System.exit called, status: 0
I/AndroidRuntime(15895): VM exiting with result code 0, cleanup skipped.
I/WindowState(  582): WIN DEATH: Window{2789db3 u0 org.kivy.accelbasicexample/org.renpy.android.PythonActivity}
W/WindowManager(  582): Force-removing child win Window{35dc54a5 u0 SurfaceView} from container Window{2789db3 u0 org.kivy.accelbasicexample/org.renpy.android.PythonActivity}
W/WindowManager(  582): Failed looking up window
W/WindowManager(  582): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@38d9df70 does not exist
W/WindowManager(  582): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8498)
W/WindowManager(  582): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8489)
W/WindowManager(  582): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1111)
W/WindowManager(  582): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState(  582): WIN DEATH: null
I/ActivityManager(  582): Process org.kivy.accelbasicexample:python (pid 15895) has died
W/ActivityManager(  582): Force removing ActivityRecord{2c627a28 u0 org.kivy.accelbasicexample/org.renpy.android.PythonActivity t48}: app died, no saved state

```

**Comment by niavlys** [comment]
same as here:
https://github.com/kivy/plyer/issues/103

**Comment by David-Kuper** [comment]
i have the same problem , i can't resovle it.
`  java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null
                                                                           at $Proxy6.equals(Unknown Source)
                                                                           at com.example.lingyimly.aspectmodule.TraceAspect1.afterInvoked(TraceAspect1.java:95)`
