### ISSUE TITLE
java.lang.Long to java.lang.Integer

### ISSUE THREAD

**Issue by remram44** [kivy/pyjnius#157]
This is the only test failure on my machine, running Windows 7 with Java 7 i386:

```
C:\programmation\pyjnius\tests>python -m unittest discover
1: declare a TestImplem that implement Collection
2: instanciate the class, with some data
<test_proxy.TestImplem object at 0x02B99558>
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__javainterfaces__', '__javamethods__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_invoke', 'data', 'equals', 'get', 'hashCode', 'hashCode_', 'invoke', 'iterator', 'j_self', 'listIterator', 'listIteratorI', 'set', 'size', 'toArray', 'toString']
tries to get a ListIterator
iterator is <test_proxy.TestImplemIterator object at 0x02BA4238>
at index 0 value is 0
at index 1 value is 1
at index 2 value is 2
at index 3 value is 3
at index 4 value is 4
at index 5 value is 5
at index 6 value is 6
at index 7 value is 7
at index 8 value is 8
3: Do cast to a collection
<java/util/Collection at 0x2b9dc60 jclass=java/util/Collection jself=<LocalRef obj=0xa1b5620 at 0x224f1e0>>
4: Try few method on the collection
reverse
None
[9L, 8L, 7L, 6L, 5L, 4L, 3L, 2L, 1L, 0L]
before swap
None
after swap
[9L, 8L, 6, 7, 5L, 4L, 3L, 2L, 1L, 0L]
rotate
None
[4, 3, 2, 1, 0, 9, 8, 6L, 7L, 5]
Order of data before shuffle() [4, 3, 2, 1, 0, 9, 8, 6L, 7L, 5]
None
Order of data after shuffle() [8, 2, 0, 3, 4, 6L, 1, 9, 7L, 5]
-> Collections.max(a)
............................hi
hi jnius other string
.
.Ú..............E..
======================================================================
ERROR: test_proxy (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_proxy
Traceback (most recent call last):
  File "C:\Python2.7\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python2.7\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\programmation\pyjnius\tests\test_proxy.py", line 148, in <module>
    print Collections.max(a2)
  File "jnius_export_class.pxi", line 893, in jnius.JavaMultipleMethod.__call__ (jnius\jnius.c:23945)
  File "jnius_export_class.pxi", line 624, in jnius.JavaMethod.__call__ (jnius\jnius.c:20680)
  File "jnius_export_class.pxi", line 790, in jnius.JavaMethod.call_staticmethod (jnius\jnius.c:22522)
  File "jnius_utils.pxi", line 65, in jnius.check_exception (jnius\jnius.c:3815)
JavaException: JVM exception occurred: java.lang.Long cannot be cast to java.lang.Integer


----------------------------------------------------------------------
Ran 47 tests in 0.080s

FAILED (errors=1)
```
##

**Comment by KeyWeeUsr** [comment]
Closes after #400 fix.
