### ISSUE TITLE
Getting Java exception later

### ISSUE THREAD

**Issue by remram44** [kivy/pyjnius#158]
Trying to debug the tests on Mac OS, I noticed that I get the actual Java exception on the next Java call...

```
(venvjnius)remirampin@randy:~/Documents/programming/pyjnius/tests$ python
Python 2.7.9 (default, Dec 14 2014, 10:02:06) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnius import autoclass
>>> autoclass('org.jnius.HelloWorld')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venvjnius/lib/python2.7/site-packages/jnius/reflect.py", line 150, in autoclass
    c = find_javaclass(clsname)
  File "jnius_export_func.pxi", line 23, in jnius.find_javaclass (jnius/jnius.c:13457)
jnius.JavaException: Class not found 'org/jnius/HelloWorld'
>>> autoclass('java.lang.String')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venvjnius/lib/python2.7/site-packages/jnius/reflect.py", line 156, in autoclass
    for constructor in c.getConstructors():
  File "jnius_export_class.pxi", line 625, in jnius.JavaMethod.__call__ (jnius/jnius.c:20695)
  File "jnius_export_class.pxi", line 712, in jnius.JavaMethod.call_method (jnius/jnius.c:21719)
  File "jnius_utils.pxi", line 65, in jnius.check_exception (jnius/jnius.c:3815)
jnius.JavaException: JVM exception occurred: org/jnius/HelloWorld : Unsupported major.minor version 52.0
>>> autoclass('java.lang.String')
<class 'jnius.reflect.java.lang.String'>
```

As you can see, I get the actual error message on the first import of `java.lang.String`. Then the second import of `java.lang.String` goes through.

This also means that pyjnius master works fine on OSX, I just need to use matching JDK and JRE versions.
##

**Comment by remram44** [comment]
(using 1.6 JDK javac:)
```
======================================================================
ERROR: test_proxy (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_proxy
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/remirampin/Documents/programming/pyjnius/tests/test_proxy.py", line 153, in <module>
    TestBadSignature()
  File "jnius_proxy.pxi", line 42, in jnius.PythonJavaClass.__init__ (jnius/jnius.c:25077)
  File "jnius_utils.pxi", line 32, in jnius.parse_definition (jnius/jnius.c:3510)
Exception: Invalid "]" character in definition "Landroid/bluetooth/BluetoothDevice;IB[])V"


----------------------------------------------------------------------
Ran 47 tests in 0.031s

FAILED (errors=1)
```
1/47 failed test

**Comment by KeyWeeUsr** [comment]
Using the latest master it works fine for me on OSX. Check the latest instructions from the docs for installing.
