### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by thugliffe** [kivy/pyjnius#168]
I have a java class with a method which takes string as an argument. The way i call it from my python file is as : 

``` python
String = autoclass(b'java.lang.String')
try:
    search_query = String(string_parameter)
except ValueError:
    pass
response = MyJavaCLass.function(string_parameter)
```

But, however when the parameter contains unicode text, it is throwing error 
_UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)_
in the line where the java function is called. 
##

**Comment by remram44** [comment]
I'm pretty sure this behaves as expected -- just use unicode objects for unicode data (e.g. u"" prefix for literals).

**Comment by thugliffe** [comment]
I did use the unicode prefix but still no luck. The sample code is as 
```python
from jnius import autoclass
String = autoclass(b'java.lang.String')
abc =String(u'åäö')
```
but still i get the same exception 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnius_export_class.pxi", line 155, in jnius.JavaClass.__init__ (jnius/jnius.c:14751)
  File "jnius_export_class.pxi", line 231, in jnius.JavaClass.call_constructor (jnius/jnius.c:15861)
  File "jnius_conversion.pxi", line 18, in jnius.release_args (jnius/jnius.c:6067)
  File "jnius_conversion.pxi", line 233, in jnius.convert_jarray_to_python (jnius/jnius.c:8166)
ValueError: chr() arg not in range(256)
```

**Comment by remram44** [comment]
Yep, this is broken. The C char type cannot hold a unicode char...
