### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by dessant** [kivy/pyjnius#176]
Windows py3 installation fails with:

```python
 Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\prc\AppData\Local\Temp\pip-stwtq6na-build\setup.py", line 77, in <module>
        env_var = getenv('JAVA_HOME')
      File "C:\Users\prc\AppData\Local\Temp\pip-stwtq6na-build\setup.py", line 11, in getenv
        return val.decode('utf-8')
    AttributeError: 'str' object has no attribute 'decode'
```

**Comment by benson-basis** [comment]
OK, I can fix that. But do we want to fix android first?

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/pyjnius/pull/177, thanks @benson-basis.
