### ISSUE TITLE
How to use pyinstaller to export pyjnius

### ISSUE THREAD

**Issue by Mingo-Wild** [kivy/pyjnius#195]
I fork a project https://github.com/Mingo-Wild/tikadetect. I want to build  it into a executable file,but I get this errors:
Exception ImportError: 'No module named platform' in 'jnius.create_jnienv' ignor
ed
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 363, in load_module
    exec(bytecode, module.**dict**)
  File "C:\Python27\lib\site-packages\jnius__init__.py", line 13, in <module>
    from .reflect import *
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 363, in load_module
    exec(bytecode, module.**dict**)
  File "C:\Python27\lib\site-packages\jnius\reflect.py", line 6, in <module>
    class Class(JavaClass):
  File "jnius\jnius_export_class.pxi", line 31, in jnius.MetaJavaClass.**new** (
jnius\jnius.c:9243)
  File "jnius\jnius_export_class.pxi", line 51, in jnius.MetaJavaClass.resolve_c
lass (jnius\jnius.c:9608)
jnius.JavaException: Unable to get the JNI Environment
tikadetect returned -1

what can i do? thank you
##

**Comment by KeyWeeUsr** [comment]
I believe you are missing JVM shared library on your path, therefore it fails to detect JNI and for some reason fails with basically nothing saying `-1` value at the end. Try to check which PyJNIus version was used for that particular application and then try to create an executable with that particular version.

Or (if it works with the new PyJNIus versions), try to package it with #373 instructions.
