### ISSUE TITLE
pyjnius incorrectly throw error on constructiong DocumentPreprocessor instance from Stanford Core NLP library.

### ISSUE THREAD

**Issue by macd** [kivy/pyjnius#196]
I am using the Stanford Core NLP libraries and I ported their ShiftReduceDemo.java to Python.
I want to create a new tokenizer from the DocumentPreprocessor class. The class constructor can take either a Reader object (but this is an abstract class), or a string that is a path name to a file. I'd like to pass in a StringReader object (subclassed from Reader) and this should be OK but pyjnius thinks it is not and throws an error.
---> 84     tokenizer = DocumentPreprocessor(StringReader(text))
     85 
     86     print('strdr class: ', strdr.__class__)

jnius/jnius_export_class.pxi in jnius.JavaClass.__init__ (jnius/jnius.c:18610)()

jnius/jnius_export_class.pxi in jnius.JavaClass.call_constructor (jnius/jnius.c:19719)()

jnius/jnius_conversion.pxi in jnius.populate_args (jnius/jnius.c:8323)()

jnius/jnius_utils.pxi in jnius.check_assignable_from (jnius/jnius.c:5607)()

JavaException: Invalid instance of 'java/io/StringReader' passed for a 'java/lang/String'

There are actually five different signatures for the constructor for DocumentPreprocessor. They are

public DocumentPreprocessor(Reader input) {
public DocumentPreprocessor(Reader input, DocType t) {
public DocumentPreprocessor(String docPath) {
public DocumentPreprocessor(String docPath) {
public DocumentPreprocessor(String docPath, DocType t) {
public DocumentPreprocessor(String docPath, DocType t, String encoding) {

I can do an ugly hack around the problem by

my_string = "It was a dark and stormy night"
Reader = autoclass("java.io.Reader")
StringReader = autoclass("java.io.StringReader")
strdr = StringReader(my_string)
strdr.__class__ = Reader

tokenizer = DocumentPreprocessor(strdr)

And this works (ugh!).  So the function check_assignable_from  is somehow not matching
the correct signatures or (sub) classes.  It would be great to have this fixed.

**Comment by danielepantaleone** [comment]
I'm having the very same problem when trying to export an ontology using OWL api: 

```
Traceback (most recent call last):
  File "jnius/jnius_export_class.pxi", line 906, in jnius.JavaMultipleMethod.__call__ (jnius/jnius.c:28436)
  File "jnius/jnius_export_class.pxi", line 632, in jnius.JavaMethod.__call__ (jnius/jnius.c:24768)
  File "jnius/jnius_conversion.pxi", line 68, in jnius.populate_args (jnius/jnius.c:8323)
  File "jnius/jnius_utils.pxi", line 207, in jnius.check_assignable_from (jnius/jnius.c:5607)
jnius.JavaException: Invalid instance of 'java/io/ByteArrayOutputStream' passed for a 'org/semanticweb/owlapi/model/OWLDocumentFormat'
```

Tried @macd hack and it works:

```python
ByteArrayOutputStream = jnius.autoclass('java.io.ByteArrayOutputStream')
OutputStream = jnius.autoclass('java.io.OutputStream')
stream = ByteArrayOutputStream()
stream.__class__ = OutputStream
```

**Comment by kived** [comment]
You should never be setting `.__class__` manually. Try `cast`ing to the correct abstract or interface: `output_stream = jnius.cast('java.io.OutputStream', stream)`

**Comment by danielepantaleone** [comment]
Works perfectly, thanks :+1:
