### ISSUE TITLE
Misleading message in Class not found exception

### ISSUE THREAD

**Issue by rhoerbe** [kivy/pyjnius#227]
pyjnius is reporting the wrong class when a depended class is not found during autoclass. However, it should report the missing class, as this problem is not obvious.

I can provide this example with a docker container if needed.

    self.pyjnius_verfiy_sig = autoclass('at.wien.ma14.pvzd.verifysigapi.PvzdVerifySig')

Traceback (most recent call last):
  File "/Users/admin/devl/pycharm/rhoerbe/PVZDpolman/PolicyManager/tests/py2java_test.py", line 48, in <module>
    py2java_test = Py2JavaTest(schema_dir_abs)
  File "/Users/admin/devl/pycharm/rhoerbe/PVZDpolman/PolicyManager/tests/py2java_test.py", line 18, in __init__
    self.pyjnius_verfiy_sig = autoclass('at.wien.ma14.pvzd.verifysigapi.PvzdVerifySig')
  File "/Users/admin/virtualenvs/pvzd34/lib/python3.4/site-packages/jnius-1.1.dev0-py3.4-macosx-10.11-x86_64.egg/jnius/reflect.py", line 154, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass (jnius/jnius.c:16446)
jnius.JavaException: Class not found b'at/wien/ma14/pvzd/verifysigapi/PvzdVerifySig'

**Comment by ljluestc** [comment]
```
from jnius import autoclass, JavaException

def safe_autoclass(class_name):
    try:
        return autoclass(class_name)
    except JavaException as e:
        # Extract the missing class information from the exception
        missing_class = e.getMessage() if e.getMessage() else "Unknown class"
        
        # Log or raise a more informative error
        raise RuntimeError(f"Could not find class: {missing_class}. "
                           f"Please ensure all dependencies are included in your classpath.") from e

# Example usage
try:
    MyClass = safe_autoclass('at.wien.ma14.pvzd.verifysigapi.PvzdVerifySig')
except RuntimeError as ex:
    print(ex)

```
