### ISSUE TITLE
Is it possible to pickle the instance of autoclass()?

### ISSUE THREAD

**Issue by tilneyyang** [kivy/pyjnius#228]
Say I have a java class `Test`

`Test = autoclass('Test')`  
`pickle.dumps(Test())`
Traceback (most recent call last):
    pickle.dumps(Test())
  File "/usr/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib/python2.7/copy_reg.py", line 71, in _reduce_ex
<class 'jnius.reflect.Test'>
   state = base(self)
  File "jnius/jnius_export_class.pxi", line 153, in jnius.JavaClass.__init__ (jnius/jnius.c:18758)
AttributeError: 'jnius.JavaClass' object has no attribute '__cls_storage'`

Is it possible to pickle the instance? I think it's neccesary when using pyjnius under multiprocessing environment.
##

**Comment by tito** [comment]
I've no idea if it's possible to pickle an instance. The first step would be to see if the Java instance can be serialized itself.

That it a little bit out of the scope of pyjnius anyway.
