### ISSUE TITLE
pyjnius counldn't work

### ISSUE THREAD

**Issue by deepzf** [kivy/pyjnius#238]
Traceback (most recent call last):
  File "test_assignable.py", line 5, in <module>
    from jnius import autoclass, JavaException
  File "build/bdist.linux-armv7l/egg/jnius/**init**.py", line 13, in <module>
  File "build/bdist.linux-armv7l/egg/jnius/reflect.py", line 14, in <module>
  File "/usr/lib/python2.7/dist-packages/six.py", line 721, in **new**
    return meta(name, bases, d)
  File "jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.**new** (jnius/jnius.c:15747)
  File "jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class (jnius/jnius.c:16135)
  File "jnius_env.pxi", line 11, in jnius.get_jnienv (jnius/jnius.c:3224)
  File "jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv (jnius/jnius.c:3158)
  File "jnius_jvm_dlopen.pxi", line 45, in jnius.create_jnienv (jnius/jnius.c:2591)
  File "/usr/lib/python2.7/UserDict.py", line 23, in **getitem**
    raise KeyError(key)
KeyError: 'JAVA_HOME'

I checked the path of javahome,it's right.
here is the code ,most basic:

from jnius import autoclass

Stack = autoclass('java.util.Stack')
stack = Stack()
stack.push('hello')
stack.push('world')

print stack.pop()
print stack.pop()
##

**Comment by deepzf** [comment]
my java enveriment:pi@raspberrypi:~/Downloads/pyjnius$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-2~deb8u1+rpi1)
OpenJDK Zero VM (build 24.95-b01, interpreted mode)
os:Raspbian
path set:
pi@raspberrypi:~/Downloads/pyjnius$ echo $JAVA_HOME
/usr/lib/jvm/java-7-openjdk-armhf
pi@raspberrypi:~/Downloads/pyjnius$ echo $CLASSPATH
.:/usr/lib/jvm/java-7-openjdk-armhf/lib/dt.jar:/usr/lib/jvm/java-7-openjdk-armhf/lib/tools.jar

**Comment by mixmastamyk** [comment]
If I had to guess I'd say that the variable is not exported, or the folder is wrong.  The "-armhf" part does look wrong.

**Comment by Arnie97** [comment]
Please check the environment variables in your script to make sure they have been exported:
```python
import os
print os.environ.get('JAVA_HOME')
```

**Comment by Petar-Luketina** [comment]
@Arnie97 Hey Arnie! I think you're on to something! When I typed in:
```
import os
print os.environ.get('JAVA_HOME')
```
it returned as `None`. I'm working to run an app in PyCharm.

**How can I get it to find the right path?**

I've already edited my bashrc file by typing in:
```
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
export PATH=$JAVA_HOME/bin:$PATH
```
but the problem still persists. I would appreciate any input. Thank you!

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/pyjnius/issues/199#issuecomment-443013378. You already got the *how* for setting the path, but it appears to me your editor isn't picking it. Perhaps check whether you can set environment variables within the editor too and add the path there.
