### ISSUE TITLE
Java class remembers one of the instances

### ISSUE THREAD

**Issue by kamathln** [kivy/pyjnius#246]
I am not a java dev, but this looked too weird to me to be normal. Note that I keep switching between calling pop on instance(stack1/stack2) or class itself (Stack). And pop works on the class (Stack) as if it remembers the last object of its class on which we operated.

```
kamathln@laxX550L:~/exp/python$ ipython
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from jnius import autoclass

In [2]: Stack=autoclass('java.util.Stack')

In [3]: stack1 = Stack()

In [4]: stack1.push('item1')
Out[4]: 'item1'

In [5]: stack1.toArray()
Out[5]: ['item1']

In [6]: Stack.pop()
Out[6]: 'item1'

In [7]: stack1.toArray()
Out[7]: []

In [8]: stack2=Stack()

In [9]: Stack.push('item2')
Out[9]: 'item2'

In [10]: stack2.toArray()
Out[10]: ['item2']

In [11]: stack1.push('item3')
Out[11]: 'item3'

In [12]: Stack.pop()
Out[12]: 'item2'

In [13]: stack1.toArray()
Out[13]: ['item3']

In [14]: Stack.pop()
Exception in thread "main" java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:85)
	at java.util.Stack.pop(Stack.java:67)
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-14-9d830963ac94> in <module>()
----> 1 Stack.pop()

/usr/local/lib/python2.7/dist-packages/jnius/jnius.so in jnius.JavaMethod.__call__ (jnius/jnius.c:13240)()

/usr/local/lib/python2.7/dist-packages/jnius/jnius.so in jnius.JavaMethod.call_method (jnius/jnius.c:13940)()

/usr/local/lib/python2.7/dist-packages/jnius/jnius.so in jnius.check_exception (jnius/jnius.c:2177)()

JavaException: JVM exception occured

In [15]: stack1.pop()
Out[15]: 'item3'

In [16]: Stack.pop()
Exception in thread "main" java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:85)
	at java.util.Stack.pop(Stack.java:67)
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-16-9d830963ac94> in <module>()
----> 1 Stack.pop()

/usr/local/lib/python2.7/dist-packages/jnius/jnius.so in jnius.JavaMethod.__call__ (jnius/jnius.c:13240)()

/usr/local/lib/python2.7/dist-packages/jnius/jnius.so in jnius.JavaMethod.call_method (jnius/jnius.c:13940)()

/usr/local/lib/python2.7/dist-packages/jnius/jnius.so in jnius.check_exception (jnius/jnius.c:2177)()

JavaException: JVM exception occured

In [17]: stack1.push('item4')
Out[17]: 'item4'

In [18]: Stack.pop()
Out[18]: 'item4'
```

**Comment by mithom** [comment]
your strange behaviour is caused by the fact that you call pop on the class instead of the instance. according to the java docs: https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html ,
this shouldn't veen be possible. You need to call pop and push on the instances. Not on the class. The real issue here seems to me the fact that you don't get an error on Stack.pop() or Stack.push('item')
