### ISSUE TITLE
shouldOverrideUrlLoading webview android

### ISSUE THREAD

**Issue by razzbee** [kivy/pyjnius#250]
Hello , I have successfully followed the wiki to implement the webview in android , but click was not working, after some reasearch , I think I need to override the webviewClient like this 

```
webView.setWebViewClient(new WebViewClient() {  
   @Override  
   public boolean shouldOverrideUrlLoading(WebView view, String url)  
   {  
       view.loadUrl(url);
       return false;

    }  
 });  

-------------------------------------
--UPDATE--
I tried implementing it but not working , below is the code :
```
#qpy:kivy
from kivy.app import App

from kivy.uix.widget import Widget
from kivy.clock import Clock
from jnius import autoclass,PythonJavaClass, java_method
from android.runnable import run_on_ui_thread

WebView = autoclass('android.webkit.WebView')
WebViewClient = autoclass('android.webkit.WebViewClient')
activity = autoclass('org.renpy.android.PythonActivity').mActivity

class myWebviewClient(PythonJavaClass):

    __javaclass__ = 'android/webkit/WebViewClient'

    def __init__(self):
        super(myWebviewClient, self).__init__()

    @java_method('(Landroid/webkit/WebView;Ljava/lang/String)Z')
    def shouldOverrideUrlLoading(view,url):
         view.loadUrl(url)
         return False

class Wv(Widget):
    def __init__(self, **kwargs):
        super(Wv, self).__init__(**kwargs)
        Clock.schedule_once(self.create_webview, 0)

    @run_on_ui_thread
    def create_webview(self, *args):
        webview = WebView(activity)
        settings = webview.getSettings()
        settings.setJavaScriptEnabled(True)
        settings.setUseWideViewPort(True) # enables viewport html meta tags
        settings.setLoadWithOverviewMode(True) # uses viewport
        settings.setSupportZoom(True) # enables zoom
        settings.setBuiltInZoomControls(True) # enables zoom controls
        #wvc = WebViewClient()
        webview.setWebViewClient(myWebviewClient())
        activity.setContentView(webview)
        webview.loadUrl('http://beta.html5test.com')

class ServiceApp(App):
    def build(self):
        return Wv()

if __name__ == '__main__':
    ServiceApp().run()
```

I get this error after I  run it :
 Traceback (most recent call last):
   File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/android/runnable.py", line 34, in run
   File ".last_tmp.py", line 43, in create_webview
     webview.setWebViewClient(myWebviewClient

Please Urgent Help is required

**Comment by razzbee** [comment]
The issue was from qpython, kivy launcher worked
