### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by arjunsingri** [kivy/pyjnius#252]
I have written a simple test for pyjnius and its failing with the following exception:

```
nsadmin@lcalarmmanager:~$ export CLASSPATH="/opt/ns/cfg/druid-processing-0.9.1.1.jar"
nsadmin@lcalarmmanager:~$ python p.py
Traceback (most recent call last):
  File "p.py", line 4, in <module>
    HyperLogLogCollector = autoclass('io.druid.query.aggregation.hyperloglog.HyperLogLogCollector')
  File "/usr/local/lib/python2.7/dist-packages/jnius-1.1_dev-py2.7-linux-x86_64.egg/jnius/reflect.py", line 154, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass (jnius/jnius.c:17391)
jnius.JavaException: Class not found 'io/druid/query/aggregation/hyperloglog/HyperLogLogCollector'
```

Contents of p.py:

```
nsadmin@lcalarmmanager:~$ cat p.py
from jnius import autoclass

HyperLogLogCollector = autoclass('io.druid.query.aggregation.hyperloglog.HyperLogLogCollector')
```

If I use the same class in a java program with the same classpath, javac is able to compile.

**Comment by arjunsingri** [comment]
Had not included all jar dependencies in the classpath.
