### ISSUE TITLE
the pypi need update

### ISSUE THREAD

**Issue by selaselah** [kivy/pyjnius#259]
python3 install error
```
Collecting jnius
  Using cached jnius-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q0/h1nvq4dn5ys54dvwtq0167kr0000gn/T/pip-build-mfbh7hy7/jnius/setup.py", line 37
        print '\n\nYou need Cython to compile Pyjnius.\n\n'
                                                          ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
```

**Comment by tito** [comment]
New version released. Use pip install pyjnius, not pip install jnius.
