### ISSUE TITLE
Cannot get pyjnius working on 64bit Windows 7, JDK 1.8.0.65 64Bit, python 2.7.9 64bit

### ISSUE THREAD

**Issue by johnverber** [kivy/pyjnius#273]
I've installed, reinstalled every....3 times.  I used dependency walker on the "jnius" directory and the only thing I see that's missing is KERNEL32.DLL.  So should I switch to a 32 bit version of java an python? 

TRACE>>>
C:\Python27\Scripts>pip install --upgrade pyjnius
Requirement already up-to-date: pyjnius in c:\python27\lib\site-packages

Requirement already up-to-date: cython in c:\python27\lib\site-packages\cython-0.25.2-py2.7-win-amd64.egg (from pyjnius)
Requirement already up-to-date: six>=1.7.0 in c:\python27\lib\site-packages\six-1.10.0-py2.7.egg (from pyjnius)

C:\Python27\Scripts>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from jnius import autoclasses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\jnius\__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: The specified module could not be found.
>>>

**Comment by johnverber** [comment]
I figured out the issue.  I was using Python27.  For some reason some of the dependencies wouldn't work on Python 2.7.  Once I switched to Python 36, everything install just fine.  Not exactly sure what the root cause was, but it fixed my issue.
