### ISSUE TITLE
Sharing autoclass is intermittently not thread-safe.

### ISSUE THREAD

**Issue by psader** [kivy/pyjnius#287]
The following example fails in a peculiar way:
````
import threading
import jnius

ArrayList = jnius.autoclass('java.util.ArrayList')

def do_array_work(tid):
    # ArrayList = jnius.autoclass('java.util.ArrayList')
    print "Running thread", tid
    try:
        n = 0
        while True:
            n += 1
            python_list = [str(tid) + "->" + str(i) for i in range(5)]
            java_arraylist = ArrayList()
            for v in python_list:
                java_arraylist.add(v)
            assert java_arraylist.size() == len(python_list)
            for i in range(java_arraylist.size()):
                x = python_list[i]
                y = java_arraylist.get(i)
                assert x == y
    finally:
        msg = "Error({0}) loops => {1} python=> {2} java=> {3}".format(
                                tid, n, python_list, java_arraylist.toArray())
        print msg
        jnius.detach()


def main():
    thread_count = 2
    threads = []
    for tid in range(thread_count):
        t = threading.Thread(target = do_array_work, args = (tid, ))
        t.start()
        threads.append(t)
    while True:
        pass

if __name__ == "__main__":
        main()
````
If you run the above code (in my case, on linux), you'll quickly hit a failure like this:
```
Running thread 0
Running thread 1
Error(1) loops => 94 python=> ['1->0', '1->1', '1->2', '1->3', '1->4'] java=> ['1->0', '1->1', '1->2', '1->3', '1->4', '0->3']
 Error(0) loops => 82 python=> ['0->0', '0->1', '0->2', '0->3', '0->4'] java=> ['0->0', '0->1', '0->2', '0->4']
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/bb/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/bb/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/psader/insights/kihbstosvc/jni_fail.py", line 21, in do_array_work
    x = python_list[i]
IndexError: list index out of range

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/bb/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/bb/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/psader/insights/kihbstosvc/jni_fail.py", line 19, in do_array_work
    assert java_arraylist.size() == len(python_list)
AssertionError
```
Note that in the above case, it seems that `thread 1` has a string value from `thread 0` (`0->3`). Also, there's an index range error *after* passing the assertion that the lists are of the same length.

If the definition of `ArrayList` is moved from global scope to the inside of `do_array_work`, the test works.. This may mean that thread-safety is only guaranteed by `jnius` if each thread only uses classes returned by its own calls to `autoclass`. This doesn't seem to be documented anywhere, and there's no test driver involving threads, even though `detach` is provided.

**Comment by tito** [comment]
My initial asumption was about GIL that protect Python code to be executed at the same time, and that may not work in Java. Now after rereading the issue multiple times, i don't think it's the case. Maybe it has something to do with the __call__() implementation + GIL, which may not be threadsafe. Our implementation doesn't return "BoundedFunction", but rather do the bound when __call__.
If the GIL switch within __call__, it may show this issue.

It's just a theory, i need to reproduce and debug it.
