### ISSUE TITLE
How can I use Double.class in Pyjnius

### ISSUE THREAD

**Issue by Csega** [kivy/pyjnius#293]
Hi All,

I have the following problem. I have to use an API from Python, which have the following signature in Java:

sig.getValue(Double.class, 0)

In Python, I tried to do the following:
[...]
Double = autoclass('java.lang.Double')
sig.getValue(Double, 0)
[...]

But I got the following error:
Traceback (most recent call last):
  File "[...]/java_test.py", line 113, in <module>
    main()
  File "[...]/java_test.py", line 100, in main
    print(sig.getValue(Double, 0))
  File "jnius/jnius_export_class.pxi", line 638, in jnius.JavaMethod.__call__ (jnius\jnius.c:25527)
  File "jnius/jnius_export_class.pxi", line 715, in jnius.JavaMethod.call_method (jnius\jnius.c:26510)
  File "jnius/jnius_utils.pxi", line 93, in jnius.check_exception (jnius\jnius.c:4618)
jnius.JavaException: JVM exception occurred: 1

What could be the problem? Please help!

Cheers!

**Comment by KeyWeeUsr** [comment]
Ref #392, you need to use `Double.__javaclass__`.
