### ISSUE TITLE
autoclass appears to construct the target class multiple times during intialization?

### ISSUE THREAD

**Issue by fake-name** [kivy/pyjnius#297]
I'm flailing about trying to use pyjnius to call functions from the [JDownloader project](http://jdownloader.org/knowledge/wiki/development/get-started).

Basically, I have a bunch of precompiled *.jar/*.class files, and I want to use functionality out of them. 

I'm executing the following script:

```

import logging
import os.path

log = logging.getLogger("Main.Jnius-Interface.Config")

jd_root = '/media/Storage/Scripts/jd'


class_path_entries = []

class_path_entries.append(os.path.join(jd_root, 'jd', 'plugins', 'decrypter'))
class_path_entries.append(os.path.join(jd_root, 'jd', 'plugins', 'hoster'))
class_path_entries.append(os.path.join(jd_root, 'libs'))
class_path_entries.append(os.path.join(jd_root, 'Core.jar'))
class_path_entries.append(os.path.join(jd_root, 'JDownloader.jar'))
class_path_entries.append(os.path.join(jd_root))

log.debug("Have %s classpath entries", len(class_path_entries))

import jnius_config
jnius_config.add_options('-Xrs', '-Xmx4096m')
jnius_config.set_classpath(*class_path_entries)

log.debug("Starting up JVM")
import jnius
from jnius import autoclass

log.debug("JVM has started")


plg_info_cls = autoclass("org.jdownloader.extensions.ExtensionController")
print(plg_info_cls)


```

However, this fails:

```

<snip a bunch of generic logging>

java.lang.IllegalStateException: You cannot init the configinterface interface org.appwork.utils.logging2.LogConfig twice
        at org.appwork.storage.config.handler.StorageHandler.addStorageHandler(StorageHandler.java:438)
        at org.appwork.storage.config.handler.StorageHandler.<init>(StorageHandler.java:331)
        at org.appwork.storage.config.JsonConfig.create(JsonConfig.java:129)
        at org.appwork.utils.logging2.LogSourceProvider.<init>(LogSourceProvider.java:133)
        at org.jdownloader.logging.LogController.<init>(LogController.java:57)
        at org.jdownloader.logging.LogController.<clinit>(LogController.java:26)
        at org.jdownloader.extensions.ExtensionController.<init>(ExtensionController.java:80)
        at org.jdownloader.extensions.ExtensionController.<clinit>(ExtensionController.java:59)
Traceback (most recent call last):
  File "test_junshorten.py", line 6, in <module>
    import junshorten
  File "/media/Storage/Scripts/unshortenit/junshorten/__init__.py", line 23, in <module>
    plg_info_cls = autoclass("org.jdownloader.extensions.ExtensionController")
  File "/usr/local/lib/python3.5/dist-packages/jnius/reflect.py", line 158, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass (jnius/jnius.c:17415)
jnius.JavaException: Class not found b'org/jdownloader/extensions/ExtensionController'

```

It seems like the single `autoclass()` call is resulting in the constructor of the target class being called multiple times, which breaks in this instance because the relevant class here has global internal state.

What's the proper way to do this? I basically know nothing about java.

**Comment by fake-name** [comment]
Never mind, It turns out that the underlying java classes I'm interfacing with were incorrectly reporting that there was multiple initialization. Some time with a java decompiler lead me to the actual issue.

Sorry about the spurious bug-report.
