### ISSUE TITLE
Unable to use jnius_config.set_options or jnius_config.set_classpath

### ISSUE THREAD

**Issue by brandonherzog** [kivy/pyjnius#318]
Both `jnius_config.set_options` and `jnius_config.set_classpath` overwrite the settings with a tuple whereas later code expects a list causing failures when importing `jnius`.

For example:
```
>>> import jnius_config
>>> jnius_config.set_options('-Xms64m', '-Xmx512m')
>>> import jnius
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\jnius\__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "C:\Python35\lib\site-packages\jnius\reflect.py", line 14, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "C:\Python35\lib\site-packages\six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius\jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__ (jnius\jnius.c:17558)
  File "jnius\jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class (jnius\jnius.c:17966)
  File "jnius\jnius_env.pxi", line 11, in jnius.get_jnienv (jnius\jnius.c:3325)
  File "jnius\jnius_jvm_desktop.pxi", line 55, in jnius.get_platform_jnienv (jnius\jnius.c:3256)
  File "jnius\jnius_jvm_desktop.pxi", line 31, in jnius.create_jnienv (jnius\jnius.c:2969)
AttributeError: 'tuple' object has no attribute 'append'
```

**Comment by KeyWeeUsr** [comment]
Closed by #319.
