### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8

### ISSUE THREAD

**Issue by bauerj** [kivy/pyjnius#320]
Hey,

I'm having issues with an app crashing with an error in the ART after calling a method using pyjnius.

This is the code that causes the error:

```python
PythonActivity = autoclass('org.kivy.android.PythonActivity')
Context = autoclass('android.content.Context')
activity = PythonActivity.mActivity
fingerprintManager = activity.getSystemService(Context.FINGERPRINT_SERVICE)
```

The last line triggers the error. After removing it, the app doesn't crash.

Full stack trace:

```logcat
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x6a
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]     string: '�jav'
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]     input: '0xe4 <0x6a> 0x61 0x76'
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]     in call to NewStringUTF
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]     from int org.libsdl.app.SDLActivity.nativeInit(java.lang.Object)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470] "SDLThread" prio=5 tid=14 Runnable
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x12d1a430 self=0xdd393700
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   | sysTid=14231 nice=0 cgrp=default sched=0/0 handle=0xcfcff920
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 6074562315 447220401 2852 ) utm=550 stm=56 core=3 HZ=100
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   | stack=0xcfbfd000-0xcfbff000 stackSize=1038KB
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #00 pc 0035b349  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #01 pc 0033b71d  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+304)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #02 pc 0023dd4b  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+846)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #03 pc 0023e283  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+58)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #04 pc 000cc653  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+42)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #05 pc 000ccfd7  /system/lib/libart.so (_ZN3art11ScopedCheck14CheckUtfStringEPKcb+870)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #06 pc 000cc5c9  /system/lib/libart.so (_ZN3art11ScopedCheck17CheckNonHeapValueEcNS_12JniValueTypeE+108)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #07 pc 000cb2bf  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+130)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #08 pc 000ca729  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+800)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #09 pc 000c66af  /system/lib/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+446)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   native: #10 pc 00044cad  /data/data/org.electrum.electrum/files/app/crystax_python/site-packages/jnius/jnius.so (???)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   at org.libsdl.app.SDLActivity.nativeInit(Native method)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   at org.libsdl.app.SDLMain.run(SDLActivity.java:936)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470]   at java.lang.Thread.run(Thread.java:761)
12-22 11:16:50.786 14209 14231 F art     : art/runtime/java_vm_ext.cc:470] 
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423] Runtime aborting...
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423] Aborting thread:
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423] "SDLThread" prio=5 tid=14 Native
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   | group="" sCount=0 dsCount=0 obj=0x12d1a430 self=0xdd393700
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   | sysTid=14231 nice=0 cgrp=default sched=0/0 handle=0xcfcff920
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   | state=R schedstat=( 6099484345 447373734 2855 ) utm=551 stm=58 core=3 HZ=100
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   | stack=0xcfbfd000-0xcfbff000 stackSize=1038KB
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   | held mutexes= "abort lock"
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #00 pc 0035b349  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #01 pc 0033b71d  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+304)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #02 pc 0032e6fd  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+24)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #03 pc 0032e585  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+424)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #04 pc 00322a31  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #05 pc 000b6b69  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1176)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #06 pc 0023e02d  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1584)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #07 pc 0023e283  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+58)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #08 pc 000cc653  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+42)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #09 pc 000ccfd7  /system/lib/libart.so (_ZN3art11ScopedCheck14CheckUtfStringEPKcb+870)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #10 pc 000cc5c9  /system/lib/libart.so (_ZN3art11ScopedCheck17CheckNonHeapValueEcNS_12JniValueTypeE+108)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #11 pc 000cb2bf  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+130)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #12 pc 000ca729  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+800)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #13 pc 000c66af  /system/lib/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+446)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   native: #14 pc 00044cad  /data/data/org.electrum.electrum/files/app/crystax_python/site-packages/jnius/jnius.so (???)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   at org.libsdl.app.SDLActivity.nativeInit(Native method)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   at org.libsdl.app.SDLMain.run(SDLActivity.java:936)
12-22 11:16:50.877 14209 14231 F art     : art/runtime/runtime.cc:423]   at java.lang.Thread.run(Thread.java:761)
```

Further information:
[▼ buildozer.spec](https://github.com/kivy/pyjnius/files/1582223/buildozer.spec.txt)
[▼ logcat.txt](https://github.com/kivy/pyjnius/files/1582219/logcat.txt)

**Comment by kuzeyron** [comment]
buildozer.spec:
```
# (list) Permissions - leaving the INTERNET if you need it for connecting to the internet.
android.permissions = INTERNET, USE_FINGERPRINT

# (int) Android API to use
android.api = 26

# (int) Android SDK version to use
android.sdk = 24

# (str) Android NDK directory (if empty, it will be automatically downloaded. Better if you download it manually)
android.ndk_path = /home/user/.buildozer/android-ndk
```

Good luck!

**Comment by bauerj** [comment]
Thanks! Apparently the crystax NDK doesn't support SDK level 24 though 😕

**Comment by kuzeyron** [comment]
I think you should stick to Python2 in this case.

**Comment by bauerj** [comment]
That's not an option for me since the rest of the [app](https://github.com/spesmilo/electrum) is not compatible to Python 2 any more.

Luckily this feature isn't that important but what are the chances that this will be supported in the near future?

**Comment by kuzeyron** [comment]
We are a couple of volunteers who is trying to implement this to later be used in Plyer.
But we are not even close to have one working just yet.

**Comment by bauerj** [comment]
That sounds great but doesn't Plyer also use pyjnius under the hood?

**Comment by kuzeyron** [comment]
Yes it does. It uses the iOS API's and Android API's for cross using.
Scroll down a little so you can see what is supported: [Plyer on Github](https://github.com/kivy/plyer/)

We should move this conversation onto IRC instead of filling this thread up.
I hope you can close this thread for now.
