### ISSUE TITLE
Running setup.py install for pyjnius ... error

### ISSUE THREAD

**Issue by loneyao** [kivy/pyjnius#321]
C:\Users\Administrator>pip install pyjnius
Collecting pyjnius
  Using cached pyjnius-1.1.1.tar.gz
Requirement already satisfied: six>=1.7.0 in c:\python\lib\site-packages (from p
yjnius)
Requirement already satisfied: cython in c:\python\lib\site-packages (from pyjni
us)
Installing collected packages: pyjnius
  Running setup.py install for pyjnius ... error
Exception:
Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\compat\__init__.py", line 73, in console
_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid
 continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python\lib\site-packages\pip\req\req_install.py", line 878, in instal
l
    spinner=spinner,
  File "c:\python\lib\site-packages\pip\utils\__init__.py", line 676, in call_su
bprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python\lib\site-packages\pip\compat\__init__.py", line 75, in console
_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid
 continuation byte

C:\Users\Administrator>

**Comment by Arnie97** [comment]
IMHO that's a problem with your pip installation, and have nothing to do with pyjnius.

Could you please reinstall your pip with `python -m pip install -I pip` and try again?

**Comment by KeyWeeUsr** [comment]
Yeah, I agree, this isn't a `pyjnius` related issue. Either you have a broken `pip` installation or there is a non-ASCII path used in `pip`. You can try to reinstall and if that does not help, you'll either need to use [`PYTHONIOENCODING=UTF8`](https://docs.python.org/2.7/using/cmdline.html?highlight=ENCODING) as an environement variable or install in a different location or switch to Python 3.
