### ISSUE TITLE
Getting exception when trying to hide Android buttons

### ISSUE THREAD

**Issue by LarsDu** [kivy/pyjnius#337]
I've been building a kivy project, and I've been trying to use the following code to hide the android soft buttons:

```

if __name__ in ("__main__","__android__"):
    if platform in ('linux','windows','macosx'):
        Window.size = (params.screen_width, params.screen_height)
    else:
        Window.fullscreen = 'auto'
        if platform == 'android':
            #Hide android soft buttons                                                                                                        
            #https://www.reddit.com/r/kivy/comments/73a5a2/hide_the_android_soft_buttons/                                                     
            activity = autoclass('org.kivy.android.PythonActivity').mActivity
            #activity = autoclass('org.renpy.android.PythonActivity').mActivity                                                               
            View = autoclass('android.view.View')
            decorView = activity.getWindow().getDecorView()                                                                                  
            flags = View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY \
                    | View.SYSTEM_UI_FLAG_FULLSCREEN \
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN \
                    | View.SYSTEM_UI_FLAG_LAYOUT_STABLE \
                    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION \
                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
            decorView.setSystemUiVisibility(flags) #FIXME! This segfaults for some reason                                                     
    app = ElectricNemoApp()
    app.run()

```

When I deploy on my Google Pixel phone I get the following exception

```
04-26 09:18:45.993  2955  2974 I python  :  Traceback (most recent call last):
04-26 09:18:45.993  2955  2974 I python  :    File "/home/ladu/Code/ElectricNemo/.buildozer/android/app/main.py", line 75, in <module>
04-26 09:18:45.993  2955  2974 I python  :    File "jnius/jnius_export_class.pxi", line 638, in jnius.jnius.JavaMethod.__call__
04-26 09:18:45.994  2955  2974 I python  :    File "jnius/jnius_export_class.pxi", line 732, in jnius.jnius.JavaMethod.call_method
04-26 09:18:45.994  2955  2974 I python  :    File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception
04-26 09:18:45.995  2955  2974 I python  :  jnius.jnius.JavaException: JVM exception occurred: Only the original thread that created a view hierarchy can touch its views.

```

How do I access the "original thread"? Am I placing this code in the appropriate place? This is in main.py

**Comment by LarsDu** [comment]
Ok, it seems someone posted a solution to this earlier. I can confirm that the following solution works!
https://stackoverflow.com/questions/43159532/hiding-navigation-bar-on-android

**Comment by tshirtman** [comment]
closing as it's a solved support request, rather than a bug (or if you thin it's a bug, please clarify :))
