### ISSUE TITLE
Install Error: ascii codec

### ISSUE THREAD

**Issue by cagsurgunu** [kivy/pyjnius#341]
When i try to install pyjnius, I get UnicodeDecodeError: ascii code can't decode byte 0xf6. my machine is Windows7. I use python 2.7. How fix it?

it is my screen:
Collecting pyjnius
  Using cached https://files.pythonhosted.org/packages/34/c7/d1f800839f64f7439ca
5d746ad35063f4a65bd5390690ef9f1176a900016/pyjnius-1.1.1.tar.gz
Requirement already satisfied: six>=1.7.0 in c:\python27\lib\site-packages (from
 pyjnius) (1.11.0)
Requirement already satisfied: cython in c:\python27\lib\site-packages (from pyj
nius) (0.28.2)
Building wheels for collected packages: pyjnius
  Running setup.py bdist_wheel for pyjnius ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools,
tokenize;__file__='c:\\users\\mer~1\\appdata\\local\\temp\\pip-install-vimjkq\\p
yjnius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repl
ace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -
d c:\users\mer~1\appdata\local\temp\pip-wheel-gneu6o --python-tag cp27:
  WARNING: Not able to assign machine() = AMD64 to a cpu value!
           Using cpu = 'i386' instead!
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  copying jnius_config.py -> build\lib.win32-2.7
  creating build\lib.win32-2.7\jnius
  copying jnius\reflect.py -> build\lib.win32-2.7\jnius
  copying jnius\signatures.py -> build\lib.win32-2.7\jnius
  copying jnius\__init__.py -> build\lib.win32-2.7\jnius
  running build_ext
  cythoning jnius\jnius.pyx to jnius\jnius.c
  warning: jnius\jnius.pyx:2:0: __getslice__, __setslice__, and __delslice__ are
 not supported by Python 3, use __getitem__, __setitem__, and __delitem__ instea
d
  building 'jnius' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\mer~1\appdata\local\temp\pip-install-vimjkq\pyjnius\setup.py"
, line 206, in <module>
      'Topic :: Software Development :: Libraries :: Application Frameworks'
    File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in se
tup
      return distutils.core.setup(**attrs)
    File "c:\python27\lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line
 186, in run
      _build_ext.build_ext.run(self)
    File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line
 194, in build_extensions
      self.build_extension(ext)
    File "c:\python27\lib\distutils\command\build_ext.py", line 499, in build_ex
tension
      depends=ext.depends)
    File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
      self.initialize()
    File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
    File "c:\python27\lib\site-packages\setuptools\msvc.py", line 147, in msvc9_
query_vcvarsall
      return EnvironmentInfo(arch, ver).return_env()
    File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1256, in retur
n_env
      exists),
    File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1279, in _buil
d_paths
      return os.pathsep.join(unique_paths)
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 9: ordina
l not in range(128)

  ----------------------------------------
  Failed building wheel for pyjnius
  Running setup.py clean for pyjnius
Failed to build pyjnius
Installing collected packages: pyjnius
  Running setup.py install for pyjnius ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\mer~1\\appdata\\local\\temp\\pip-install-vimjkq\
\pyjnius\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().re
place('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --r
ecord c:\users\mer~1\appdata\local\temp\pip-record-iznc9x\install-record.txt --s
ingle-version-externally-managed --compile:
    WARNING: Not able to assign machine() = AMD64 to a cpu value!
             Using cpu = 'i386' instead!
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying jnius_config.py -> build\lib.win32-2.7
    creating build\lib.win32-2.7\jnius
    copying jnius\reflect.py -> build\lib.win32-2.7\jnius
    copying jnius\signatures.py -> build\lib.win32-2.7\jnius
    copying jnius\__init__.py -> build\lib.win32-2.7\jnius
    running build_ext
    skipping 'jnius\jnius.c' Cython extension (up-to-date)
    building 'jnius' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mer~1\appdata\local\temp\pip-install-vimjkq\pyjnius\setup.p
y", line 206, in <module>
        'Topic :: Software Development :: Libraries :: Application Frameworks'
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in
setup
        return distutils.core.setup(**attrs)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line 6
1, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\Cython\Distutils\old_build_ext.py", li
ne 186, in run
        _build_ext.build_ext.run(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\python27\lib\site-packages\Cython\Distutils\old_build_ext.py", li
ne 194, in build_extensions
        self.build_extension(ext)
      File "c:\python27\lib\distutils\command\build_ext.py", line 499, in build_
extension
        depends=ext.depends)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 147, in msvc
9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1256, in ret
urn_env
        exists),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1279, in _bu
ild_paths
        return os.pathsep.join(unique_paths)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 9: ordi
nal not in range(128)

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\mer~1\\appdata\\local\\temp\\pip-install-vimjkq\\pyjnius\\setup.py';f=ge
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
ose();exec(compile(code, __file__, 'exec'))" install --record c:\users\mer~1\app
data\local\temp\pip-record-iznc9x\install-record.txt --single-version-externally
-managed --compile" failed with error code 1 in c:\users\mer~1\appdata\local\tem
p\pip-install-vimjkq\pyjnius\

c:\Python27\Scripts>

**Comment by dolang** [comment]
Not sure what this is about, but having a quick glance at it, does your username contain an `ö`?
```
return os.pathsep.join(unique_paths)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 9: ordi
nal not in range(128)
```
Here it tries to combine 2 paths and fails, and the byte `0xf6` is an `ö` in [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), but obviously not part of [ASCII](https://en.wikipedia.org/wiki/ASCII).

And ASCII is what Python 2 uses in its source files.

By the way you can get better results when enclosing your log in triple backticks:
\`\`\`
<your log here>
\`\`\`
Then Markdown won't try to interpret its contents.

**Comment by KeyWeeUsr** [comment]
Try setting this environment variable before installing anything, it might help as it [changes the default encoding](https://stackoverflow.com/q/11741574/5994041) for the interpreter:

    set PYTHONIOENCODING=UTF-8

**Comment by KeyWeeUsr** [comment]
Also, this is not a `pyjnius` issue, but a Python one directly. You can try to install Python somewhere else (path with ASCII only characters) or upgrade to Python 3 which should be able to hand non-ASCII paths normally.
