### ISSUE TITLE
Running nosetests,  ERROR: Failure: ImportError (cannot import name 'JavaClass')

### ISSUE THREAD

**Issue by liuxiang0** [kivy/pyjnius#343]
windows 10, python 3.6.5, 64bit OS, amd64.

>nosetests
EEEEEEEEEEEEEEEEE
================================================================
ERROR: Failure: ImportError (cannot import name 'JavaClass')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python\python36\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "c:\python\python36\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "c:\python\python36\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "c:\python\python36\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "c:\python\python36\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "c:\python\python36\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\working\pyjnius\tests\test_assignable.py", line 5, in <module>
    from jnius import autoclass, JavaException
  File "c:\python\python36\lib\site-packages\pyjnius-1.1.2.dev0-py3.6-win-amd64.egg\jnius\__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "c:\python\python36\lib\site-packages\pyjnius-1.1.2.dev0-py3.6-win-amd64.egg\jnius\reflect.py", line 8, in <module>
    from jnius import (
ImportError: cannot import name 'JavaClass'

================================================================

**Comment by KeyWeeUsr** [comment]
The `JavaClass` referst to [`jnius_export_class.JavaClass`](https://github.com/kivy/pyjnius/blob/61149f20436e560cdff89e4abdd9035f8e4f7d35/jnius/jnius_export_class.pxi#L234) and since it can't import it from `jnius` through the relative import `from .jnius import *`, then the package hasn't been compiled yet and/or the compilation failed, thus the tests failed too.
