### ISSUE TITLE
Python 3.6, Cython 0.28 UnicodeDecode error

### ISSUE THREAD

**Issue by Laksh47** [kivy/pyjnius#344]
Traceback (most recent call last):
  File "jnius/jnius_export_class.pxi", line 638, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 717, in jnius.JavaMethod.call_method
  File "jnius/jnius_conversion.pxi", line 155, in jnius.convert_jobject_to_python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 53: invalid continuation byte

This issue does not exist in Python 2.7

Any work around available for Python 3.6?

**Comment by KeyWeeUsr** [comment]
Is it still happening in the latest release?
