### ISSUE TITLE
ArrayList of String array

### ISSUE THREAD

**Issue by nitishgupta** [kivy/pyjnius#349]
One of Java function's argument is ```List<String[]>```
`
jArrayList = autoclass('java.util.ArrayList')   
jString = autoclass('java.lang.String')
words = ['a', 'b', 'c']
javaWords = [jString(w)  for w in words]
arraylist = jArrayList()
arraylist.add(javaWords)
`

But I get the following `JavaException: No methods matching your arguments`

What is the solution for this?

**Comment by KeyWeeUsr** [comment]
Reproduced:

```batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnius\jnius_export_class.pxi", line 996, in jnius.JavaMultipleMethod.__call__
jnius.JavaException: No methods matching your arguments
```

but, you are trying to add a Python list into Java `ArrayList`, which might not be directly possible IMO. Anyway, I tried first converting it to `java.lang.reflect.Array` of `String`s, but the result was the same. Confirmed. No solution yet, since I think it's not implemented. :zipper_mouth_face: 

I'm not sure whether it even will be though since it's not a primitive type and there are [other most likely not supported too](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html) and any custom class you'd create e.g. `public class MyClass extends A, B, C, D, ...` is not supported too:

> Serializable, Cloneable, Iterable<E>, Collection<E>, List<E>, RandomAccess

Any ideas about what we should do with this @tito @tshirtman? Perhaps implementing it for `Object` could do?

**Comment by AbdealiJK** [comment]
I'm probably a bit confused here - the add() in an ArrayList accepts elements - https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#add(E)

So, doing a `add(pythonListWithStrings)` should throw an error, as you need to do:
```
for i in javaWords:
    arraylist.add(i)
```

**Comment by KeyWeeUsr** [comment]
@AbdealiJK Sorry, I'm not a Java guy, however I think you probably don't see the problem. You can add each element to a 1D array/list/etc, but we're talking about 2D+ or on simple terms *any* `Object` added to the `ArrayList`. PyJNIus just doesn't seem to be able to hand *any* object yet perhaps due to a missing cast of any random element to `Object` or something which might(?) trigger the "no matching arguments".

From my point of view it seems to be working properly in Java:

```java
import java.lang.String;
import java.util.Arrays;
import java.util.ArrayList;


public class stringarraylist {
    public static void main(String[] args) {
        ArrayList<Object> list = new ArrayList<Object>();
        System.out.println(list);

        String[] str_array = {"a", "b", "c"};
        System.out.println(str_array);

        // add the array of strings to the list
        list.add(str_array);
        System.out.println(list);

        ArrayList<Object> str_list = new ArrayList<>(
            Arrays.asList(str_array)
        );
        list.add(str_list);
        System.out.println(list);

        list.add(new Object());
        System.out.println(list);
    }
}
```

**Comment by AbdealiJK** [comment]
Ah, I see. I get the issue now.
This is to create a List of arrays. 
Thanks for the clarification :+1:
