### ISSUE TITLE
p4a kivy cannot build app because "patching file jnius/jnius_jvm_android.pxi" failed

### ISSUE THREAD

**Issue by JonasEc** [kivy/pyjnius#358]
I am trying to build a simple android app using kivy and p4a. The following error code occurs whenever I try to run p4a -- I have tried python2 and python3crystax, I have tried android api 15, 19, 21, 27, 28, etc, no avail, always the same error: 

`[DEBUG]:   -> running patch -t -d /home/jonasmg/.local/share/python-for-android/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /usr/local/lib/python3.6/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch
[DEBUG]:   	patching file jnius/jnius_jvm_android.pxi
[DEBUG]:   	patching file setup.py
[DEBUG]:   	Hunk #1 FAILED at 53.
[DEBUG]:   	1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
Exception in thread background thread for pid 18629:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /home/jonasmg/.local/share/python-for-android/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /usr/local/lib/python3.6/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej

  STDERR:

[INFO]:    STDOUT:
	patching file jnius/jnius_jvm_android.pxi	
patching file setup.py	
Hunk #1 FAILED at 53.	
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
[INFO]:    STDERR:
	
Traceback (most recent call last):
  File "/usr/local/bin/p4a", line 11, in <module>
    load_entry_point('python-for-android==0.6.0', 'console_scripts', 'p4a')()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/build.py", line 566, in build_recipes
    recipe.apply_patches(arch)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/recipe.py", line 486, in apply_patches
    arch.arch)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/recipe.py", line 194, in apply_patch
    "-i", filename, _tail=10)
  File "/usr/local/lib/python3.6/dist-packages/pythonforandroid/logger.py", line 175, in shprint
    for line in output:
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 720, in next
    self.wait()
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.6/dist-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /home/jonasmg/.local/share/python-for-android/build/other_builds/pyjnius-python3crystax-sdl2/armeabi-v7a/pyjnius -p1 -i /usr/local/lib/python3.6/dist-packages/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
patching file setup.py
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej

  STDERR:
`

**Comment by darosior** [comment]
Hi I ran into the same error. Have you fixed it ?

**Comment by zer0c0d3** [comment]
Me too , i got the same error ... Have fixed it anyone ????

**Comment by KeyWeeUsr** [comment]
@zer0c0d3 This has already been fixed https://github.com/kivy/python-for-android/pull/1426.
