### ISSUE TITLE
ImportError: cannot import name 'autoclass'

### ISSUE THREAD

**Issue by chadwick-hui** [kivy/pyjnius#381]
I was using anaconda python notebook. After installing jnius from here I still can't make the first step

the error was as follows:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-159-4923ad3c3ea7> in <module>()
----> 1 from jnius import autoclass
      2 
      3 
      4 

ImportError: cannot import name 'autoclass'

These are the files in the installed folder. I just want to ask if any of the pxi is missing in the following pic.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/38255626/50464485-fda57180-09cb-11e9-99d7-b23c936b99cf.png">

**Comment by KeyWeeUsr** [comment]
The package structure is ok. If you can do this: `from jedi import Script` the importing fails most likely due to missing Java paths set. macOS should have those paths already set, therefore try to check them via `os.environ`.

We have documentation for setting those paths on Windows, hopefully it'll help you. Also, make sure you have Java even installed in conda itself. I'm not quite sure if it can use the global system one. For even importing PyJNIus you obviously need Java installed.

https://pyjnius.readthedocs.io/en/latest/installation.html#installation-for-windows

**Comment by chadwick-hui** [comment]
Thanks for your reply KeyWeeUsr, I've just tried `from jedi import Script`, which worked perfectly. 

what I've got for the paths is 
'/Library/Frameworks/Python.framework/Versions/3.7/bin:
/Library/Frameworks/Python.framework/Versions/3.7/bin:
/Library/Frameworks/Python.framework/Versions/3.7/bin:
/anaconda3/bin:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin',

I'm not sure whether these are the paths that were supposed to be as it could successfully import `script`.

Only thing left is the installation of java in conda. I've installed java on my mac but im not sure how'd it be installed in conda?

Thanks

**Comment by chadwick-hui** [comment]
also, when i was trying to import in jnius in command line, the following error pops up (im not sure whether it provides more information for the original question)

`>>> from jnius import autoclass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/anaconda3/lib/python3.6/site-packages/jnius/reflect.py", line 14, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/anaconda3/lib/python3.6/site-packages/six.py", line 827, in __new__
    return meta(name, bases, d)
  File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 45, in jnius.create_jnienv
  File "/anaconda3/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'JAVA_HOME'
`

thanks!

**Comment by KeyWeeUsr** [comment]
Command line is always the first thing you should try no matter what wrapper or IDE you use when something doesn't work in your programming environment. Some editors for example need to set paths via rather hidden settings and so on.

Regarding the log, it basically tells you that you don't have `JAVA_HOME` environment variable set, therefore PyJNIus can't find Java libraries and VM. Fortunately it fails sooner, otherwise you'd probably just get a segfault instead (harder to debug).

When in command line, use `export JAVA_HOME=...` to set path to Java JDK or JRE folder. To install Java in conda just use the instructions provided [here](https://anaconda.org/conda-forge/openjdk). :)
