### ISSUE TITLE
“Unable to find a None method” in pyjnius: Executing java methods from a python script

### ISSUE THREAD

**Issue by piropiro2018** [kivy/pyjnius#410]
I am trying to call java methods from a .jar in the python script using pyjnius. 
I am facing the error "jnius.JavaException: Unable to find a None method!"

Anybody know what I'm doing wrong here?
I will appreciate your help with this situation.

Below is the code I'm running in java and the pyjnius code.

*java code*
-----------------------
``` java:Ppap.java
package yosh.ppap;

import org.kie.api.KieServices;
import org.kie.api.runtime.KieContainer;
import org.kie.api.runtime.KieSession;

import yosh.ppap.model.Apple;
import yosh.ppap.model.Pen;
import yosh.ppap.model.Pineapple;

public class Ppap {

    KieServices kieServices = KieServices.Factory.get();
    KieContainer kieContainer = kieServices.getKieClasspathContainer();
    KieSession kieSession = kieContainer.newKieSession("PpapKBase.session");

    Pen pen = new Pen();
    Apple apple = new Apple();
    Pineapple pineapple = new Pineapple();

    public void runPpap() {

        //abbreviation

    }

}
```
*python code*
-----------------------
``` python:main.py
#-*- coding: utf-8 -*-

from kivy.app import App
from kivy.uix.widget import Widget

from kivy.properties import StringProperty 
from kivy.utils import platform
from jnius import autoclass

import sqlite3
import os.path

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
_DBFILE = os.path.join(BASE_DIR, "message.db")

message = ""
select_sql = 'select body from message order by messageId desc limit 1'

class TextWidget(Widget):
    text = StringProperty()    
    Ppap = autoclass('yosh.ppap.Ppap')

    def __init__(self, **kwargs):
        super(TextWidget, self).__init__(**kwargs)
        self.text = ''

    def buttonClicked(self):        
        
        self.Ppap.runPpap()
        self._conn = sqlite3.connect(_DBFILE)

        cur = self._conn.cursor()
        cur.execute(select_sql)
        for row in cur:
            self.text = 'Hello World and ' + ''.join(map(str, row))
        cur.close()
        
class TestApp(App):
    def __init__(self, **kwargs):
        super(TestApp, self).__init__(**kwargs)
        self.title = 'greeting'

        self._conn = sqlite3.connect(_DBFILE)

        cur = self._conn.cursor()
        cur.execute(select_sql)
        for row in cur:
            message = row
        cur.close()

    def build(self):
        return TextWidget()

if __name__ == '__main__':
    TestApp().run()
```
*kivy code*
-----------------------
``` kivy:test.kv
TextWidget: 

<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        
        Label:
            id: label1
            font_size: 68
            text: root.text    

        Button:
            id: button1
            text: "OK"
            font_size: 68
            on_press: root.buttonClicked()  
```
* After building the pyjnius code at buildozerVM and running it on my acer A700 I get this error in log: *
-----------------------
``` txt
[INFO   ] Logger: Record log in /data/data/org.test.my_application2/files/app/.kivy/logs/kivy_19-02-24_0.txt
[WARNING] [Config      ] Upgrading configuration in progress.
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[INFO   ] Kivy: v1.11.0.dev0, git-Unknown, 20190212
[INFO   ] Python: v2.7.15 (default, Feb 12 2019, 04:55:52) 
[GCC 4.2.1 Compatible Android (4691093 based on r316199) Clang 6.0.2 (https://a
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[WARNING] Could not satisfy Android orientation "LandscapeLeft LandscapeRight", only {portrait,landscape} are currently supported. Defaulting to portrait
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <OpenGL ES 2.0 14.01002>
[INFO   ] GL: OpenGL vendor <NVIDIA Corporation>
[INFO   ] GL: OpenGL renderer <NVIDIA Tegra 3>
[INFO   ] GL: OpenGL parsed version: 2, 0
[INFO   ] GL: Texture max size <2048>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/app/main.py", line 56, in <module>
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/app.py", line 855, in run
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/base.py", line 502, in runTouchApp
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/core/window/window_sdl2.py", line 724, in mainloop
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/core/window/window_sdl2.py", line 459, in _mainloop
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/base.py", line 340, in idle
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/base.py", line 325, in dispatch_input
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/base.py", line 231, in post_dispatch_input
[WARNING] stderr:   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8192)
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/core/window/__init__.py", line 1360, in on_motion
[WARNING] stderr:   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8192)
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/core/window/__init__.py", line 1376, in on_touch_down
[WARNING] stderr:   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8192)
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/uix/widget.py", line 460, in on_touch_down
[WARNING] stderr:   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8192)
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/uix/widget.py", line 460, in on_touch_down
[WARNING] stderr:   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8192)
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/uix/behaviors/button.py", line 151, in on_touch_down
[WARNING] stderr:   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:8147)
[WARNING] stderr:   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch (kivy/_event.c:14036)
[WARNING] stderr:   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch (kivy/_event.c:12817)
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/platform/build/build/python-installs/my_application2/kivy/lang/builder.py", line 64, in custom_callback
[WARNING] stderr:   File "/data/data/org.test.my_application2/files/app/test.kv", line 18, in <module>
[WARNING] stderr:     on_press: root.buttonClicked()  
[WARNING] stderr:   File "/home/kivy/build/test/.buildozer/android/app/main.py", line 30, in buttonClicked
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 720, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:26849)
[WARNING] stderr:   File "jnius/jnius_export_class.pxi", line 673, in jnius.jnius.JavaMethod.ensure_method (jnius/jnius.c:26151)
[WARNING] stderr: jnius.jnius.JavaException: Unable to find a None method!
```

**Comment by piropiro2018** [comment]
It was a problem to call the method while not instantiated the class

fixed　python code

class TextWidget(Widget):
    text = StringProperty()    
    Ppap = autoclass('yosh.drools.ppap.Ppap')

>     ppap = Ppap()


    def __init__(self, **kwargs):
        super(TextWidget, self).__init__(**kwargs)
        self.text = ''

    def buttonClicked(self):       

>         self.ppap.runPpap()

        self._conn = sqlite3.connect(_DBFILE)

        cur = self._conn.cursor()
        cur.execute(select_sql)
        for row in cur:
            self.text = 'Hello World and ' + ''.join(map(str, row))
        cur.close()
