### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rajdeeprath** [kivy/pyjnius#422]
I am trying to install this on my ubuntu 16.04, but no matter what i try i keep getting error. Java is installed and running fine. other java apps are running fine. I have cython installed too. Any thoughts ?

```
{user}:~/pyjnius$ sudo /home/rajdeeprath/drpa/bin/python  setup.py install
Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    ['which', 'javac']
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1

```

Typing which java in shell gives me this:

`/usr/lib/jvm/java-8-openjdk-amd64/bin/java`

**Comment by rajdeeprath** [comment]
NVM, my mistake should have spent more time googling. Apparently, the default jre install that is enough for running java apps does not have `javac`. I had to run the following command to get javac : 

`sudo apt-get install openjdk-8*`
