### ISSUE TITLE
ValueError: chr() arg not in range(0x110000)

### ISSUE THREAD

**Issue by Chriskamphuis** [kivy/pyjnius#437]
`JString` does not seem to handle all characters correctly:

This code snippet will result in the error:
```
from jnius import autoclass
JString = autoclass('java.lang.String')
JString('ö')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnius/jnius_export_class.pxi", line 256, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 341, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 24, in jnius.release_args
  File "jnius/jnius_conversion.pxi", line 288, in jnius.convert_jarray_to_python
ValueError: chr() arg not in range(0x110000)
```

**Comment by Chriskamphuis** [comment]
This solves the problem:

`JString('ö'.encode('utf-8'))`

But I do not know if this behavior is desired?

**Comment by hx2A** [comment]
I'm working on a fix for this in PR #524.

**Comment by hx2A** [comment]
@tshirtman I think you can close this issue now because of #524 . One of my unittests verifies this specific thing.

**Comment by tshirtman** [comment]
great, thanks :)
