### ISSUE TITLE
Java class not found when deserializing with ObjectInputStream

### ISSUE THREAD

**Issue by TovlyDeutsch** [kivy/pyjnius#453]
I'm using the Stanford Parser with pyjnius. Using the `autoclass` function of pyjnius, I can use the java classes from the parser. However, when I try to deserialize something that uses those classes, I get a `ClassNotFoundException`. How could I ensure that the jvm has access to the the class when deserializing (calling `readObject`)?

**This works fine**

    ArrayList = autoclass('java.util.ArrayList')
    ScoredObject = autoclass('edu.stanford.nlp.util.ScoredObject')
    sensTrees = ArrayList()
    sensTrees.add(ScoredObject(ArrayList(), 5))
    outFile = FileOutputStream('javaParses.ser')
    oos = ObjectOutputStream(outFile)
    oos.writeObject(sensTrees)

**But this throws the error below**

    inFile = FileInputStream('javaParses.ser')
    ois = ObjectInputStream(inFile)
    Docs = ois.readObject() // this line throws the error

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\we890\seniorThesis\parseDocs.py", line 75, in test
    Docs = ois.readObject()
  File "jnius\jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius\jnius_export_class.pxi", line 843, in jnius.JavaMethod.call_method
  File "jnius\jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: edu.stanford.nlp.util.ScoredObject
```

**Older Error (I think from a different jdk and pyjinius version)**

    java.lang.ClassNotFoundException: edu.stanford.nlp.util.ScoredObject

**Comment by tueda** [comment]
I hit the same issue. To reproduce it, a concrete example with Guava is here:
```python
import jnius_config
jnius_config.set_classpath('guava-28.2-jre.jar')
from jnius import autoclass

Stats = autoclass('com.google.common.math.Stats')

ByteArrayOutputStream = autoclass('java.io.ByteArrayOutputStream')
ObjectOutputStream = autoclass('java.io.ObjectOutputStream')
ByteArrayInputStream = autoclass('java.io.ByteArrayInputStream')
ObjectInputStream = autoclass('java.io.ObjectInputStream')

a = Stats.of(1, 2, 3)

# Of course, it works.
# print(a.toString())
# print()

b_out = ByteArrayOutputStream()
o_out = ObjectOutputStream(b_out)
o_out.writeObject(a)
b_array = b_out.toByteArray()

b_in = ByteArrayInputStream(b_array)
o_in = ObjectInputStream(b_in)

try:
    b = o_in.readObject()
except Exception as e:
    print(e)
    print()
    print(e.classname)
    print()
    print(e.innermessage)
    print()
    for x in e.stacktrace:
        print(x)
```
```
JVM exception occurred: com.google.common.math.Stats

java.lang.ClassNotFoundException

com.google.common.math.Stats

java.lang.ClassNotFoundException: com.google.common.math.Stats
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
java.base/java.lang.Class.forName0(Native Method)
java.base/java.lang.Class.forName(Class.java:398)
java.base/java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:693)
java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1886)
java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
```
where I used
```
Python 3.7.6
pyjnius 1.2.1
openjdk 11.0.4 2019-07-16
```

**Comment by tueda** [comment]
Somehow the system class loader and the context class loader, which can be found by
```python
print(autoclass('java.lang.ClassLoader').getSystemClassLoader())
print(autoclass('java.lang.Thread').currentThread().getContextClassLoader())
```
is not used for `ObjectInputStream`:
```python
print(o_in.getClass().getClassLoader())
```
(The last one becomes `None`.)

I am still not sure why it happens with Pyjnius, but then [JDK-4340158](https://bugs.openjdk.java.net/browse/JDK-4340158) is relevant, and a workaround would be creating a custom class extending `ObjectInputStream`: https://stackoverflow.com/a/12180547. I also found it was an issue in Scala, scala/bug#9237.
