### ISSUE TITLE
ImportError - Python 3.8 compatibility?

### ISSUE THREAD

**Issue by Csega** [kivy/pyjnius#456]
I have pyjnius installed with Python3.7 (64 bit on a 64 bit Windows 10 machine, Java SE JDK version: 1.8.0_221), which works correctly. I updated my Python version to 3.8 (64 bit), installed all the packages I needed (pyjnius is among them), and pyjnius stopped working. I have the same path, the same Java version installed, everything. I checked and in principle with Python3.8 I can see every needed dll in the PATH and still I get the following error:

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\jnius\__init__.py", line 12, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed while importing jnius"

In Python 3.7 everything still works correctly. What could be the problem? Is it something to do with Python 3.8 compatbility? Or is it something else? I checked other issues here with ImportError, but it seems that I have everything in the path which is needed. I even checked the dependencies with Dependencies (`https://github.com/lucasg/Dependencies`), and it seems that everthing is present in the path, which is needed.

**Comment by Csega** [comment]
I was unaware of this change. Thank you very much! :)
