### ISSUE TITLE
Can't install pyjnius on macOS, says missing JVM

### ISSUE THREAD

**Issue by hrubiak** [kivy/pyjnius#458]
I'm trying to install pyjnius on macOS Catalina. I get an error about missing JVM, no Java runtime present. I do have java installed (java 8 update 231) though.
Here's the error:

ERROR: Command errored out with exit status 1:
     command: /Users/ross/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dh/02hmcv7x1157fy4jjvdf4dqr0000gn/T/pip-install-4ta9qcmr/pyjnius/setup.py'"'"'; __file__='"'"'/private/var/folders/dh/02hmcv7x1157fy4jjvdf4dqr0000gn/T/pip-install-4ta9qcmr/pyjnius/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dh/02hmcv7x1157fy4jjvdf4dqr0000gn/T/pip-install-4ta9qcmr/pyjnius/pip-egg-info
         cwd: /private/var/folders/dh/02hmcv7x1157fy4jjvdf4dqr0000gn/T/pip-install-4ta9qcmr/pyjnius/
    Complete output (7 lines):
    Unable to find any JVMs matching version "(null)".
    No Java runtime present, try --request to install.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dh/02hmcv7x1157fy4jjvdf4dqr0000gn/T/pip-install-4ta9qcmr/pyjnius/setup.py", line 117, in <module>
        raise Exception('You must install Java on your Mac OS X distro')
    Exception: You must install Java on your Mac OS X distro
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by hrubiak** [comment]
Actually I'm getting the same error on Windows 10 and an older version of macOS.
