### ISSUE TITLE
WebView issue

### ISSUE THREAD

**Issue by Juphex** [kivy/pyjnius#472]
Hi,
I got a problem with android.webkit.WebView.
The code 
```
from kivy.app import App
from kivy.uix.screenmanager import Screen
from kivy.uix.button import Button
from jnius import autoclass, cast

activity = autoclass("org.kivy.android.PythonActivity").mActivity
context = cast("android.content.Context", activity.getApplicationContext())

class Test(Screen):
    def __init__(self):
        WebView = autoclass("android.webkit.WebView")
        wv = WebView(activity)
        wv.loadUrl("https://google.de")


    def switch_screen(self, instance):
        self.manager.current = "view"

class App(App):
    def build(self):
        return Test()


```

The error log from adb

```
12-30 23:50:21.794 26046 26072 W ResourceType: No package identifier when getting name for resource number 0x00000000

12-30 23:50:21.808 26046 26072 I WebViewFactory: Loading com.android.chrome version 79.0.3945.93 (code 394509337)

12-30 23:50:22.096 26046 26072 I cr_LibraryLoader: Time to load native libraries: 8 ms

12-30 23:50:22.134 26046 26072 W ResourceType: No package identifier when getting name for resource number 0x00000000

12-30 23:50:22.151 26046 26072 I python  : [INFO   ] [Base        ] Leaving application in progress...
12-30 23:50:22.152 26046 26072 I python  :  Traceback (most recent call last):
12-30 23:50:22.153 26046 26072 I python  :    File "/home/a/test/.buildozer/android/app/main.py", line 19, in <module>
12-30 23:50:22.154 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
12-30 23:50:22.156 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
12-30 23:50:22.158 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
12-30 23:50:22.160 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
12-30 23:50:22.161 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 342, in idle
12-30 23:50:22.163 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 327, in dispatch_input
12-30 23:50:22.165 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 233, in post_dispatch_input
12-30 23:50:22.166 26046 26072 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 23:50:22.168 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/__init__.py", line 1402, in on_motion
12-30 23:50:22.170 26046 26072 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 23:50:22.171 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/__init__.py", line 1418, in on_touch_down
12-30 23:50:22.173 26046 26072 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 23:50:22.174 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/uix/screenmanager.py", line 1191, in on_touch_down
12-30 23:50:22.176 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/uix/widget.py", line 549, in on_touch_down
12-30 23:50:22.177 26046 26072 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 23:50:22.178 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/uix/relativelayout.py", line 288, in on_touch_down
12-30 23:50:22.180 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/uix/widget.py", line 549, in on_touch_down
12-30 23:50:22.181 26046 26072 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
12-30 23:50:22.183 26046 26072 I python  :    File "/home/a/test/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/uix/behaviors/button.py", line 151, in on_touch_down
12-30 23:50:22.184 26046 26072 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
12-30 23:50:22.186 26046 26072 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
12-30 23:50:22.187 26046 26072 I python  :    File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
12-30 23:50:22.188 26046 26072 I python  :    File "/home/a/test/.buildozer/android/app/settings_screen.py", line 23, in webview
12-30 23:50:22.190 26046 26072 I python  :    File "jnius/jnius_export_class.pxi", line 256, in jnius.jnius.JavaClass.__init__
12-30 23:50:22.191 26046 26072 I python  :    File "jnius/jnius_export_class.pxi", line 343, in jnius.jnius.JavaClass.call_constructor
12-30 23:50:22.192 26046 26072 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
12-30 23:50:22.193 26046 26072 I python  :  jnius.jnius.JavaException: JVM exception occurred: Did not yet override the UI thread

```

**Comment by Juphex** [comment]
Solved it using
```
        webview = WV(activity)
        webview.getSettings().setJavaScriptEnabled(True)
        webview.setWebChromeClient(ChromeClient())
        webview.setWebViewClient(WebViewClient())
        webview.loadUrl('https://www.google.com/')
```
