### ISSUE TITLE
How to import a custom jar in a python script?

### ISSUE THREAD

**Issue by jfabdo** [kivy/pyjnius#487]
Maybe I'm missing something, but I haven't seen this in the docs anywhere.

I have a simple script that looks like this:

```
from jnius import autoclass

Service = autoclass('name_of_jar')
```

When I run it, I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    Service = autoclass('name_of_jar')
  File "/usr/local/lib/python3.7/site-packages/jnius/reflect.py", line 208, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 28, in jnius.find_javaclass
jnius.JavaException: Class not found b'name_of_jar'
```

Is there something else I need to do to point autoclass to my jar?

**Comment by jfabdo** [comment]
Oh, it's by package name. That's confusing.
