### ISSUE TITLE
More on libjvm.so resolution, on linux, when JAVA_HOME is set.

### ISSUE THREAD

**Issue by cmacdonald** [kivy/pyjnius#537]
I have set JAVA_HOME variable, but jnius goes hunting in `/usr/lib/jvm/`.
It then uses JAVA_HOME as `/local/trmaster/opt/jdk-11.0.6/`, but fails to pick up the correct location of the .so file.

```
DEBUG:jnius.env:looing for libjvm to initiate pyjnius, cpu is amd64, platform is linux
DEBUG:jnius.env:found libjvm.so at /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.77-0.b03.el7_2.x86_64/jre/lib/amd64/server/libjvm.so
Traceback (most recent call last):
  File "RQ1-anserini_opt-cw09.py", line 5, in <module>
    pt.init(boot_packages=["io.anserini:anserini:0.9.2:fatjar"])
  File "/users/tr.craigm/projects/pyterrier/pyterrier/pyterrier/__init__.py", line 70, in init
    from jnius import autoclass, cast
  File "/users/tr.craigm/anaconda3/envs/pyterrier/lib/python3.6/site-packages/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/users/tr.craigm/anaconda3/envs/pyterrier/lib/python3.6/site-packages/jnius/reflect.py", line 20, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/users/tr.craigm/anaconda3/envs/pyterrier/lib/python3.6/site-packages/six.py", line 856, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 119, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 179, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 134, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 101, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/local/trmaster/opt/jdk-11.0.6/jre/lib/amd64/server/libjvm.so': b'/local/trmaster/opt/jdk-11.0.6/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory'
$echo $JAVA_HOME
/local/trmaster/opt/jdk-11.0.6/

```

JVM_PATH does not help.
The RuntimeError in env.py is not raised.

The actual location of the so file is:
`/local/trmaster/opt/jdk-11.0.6/lib/server/libjvm.so`

**Comment by cmacdonald** [comment]
`get_jnius_lib_location()` and friends in env.py - why dont we pass the JAVA_HOME into that function that was identified in jnius_jvm_dlopen.pxi?

**Comment by cmacdonald** [comment]
![image](https://user-images.githubusercontent.com/620938/83143719-46de8100-a0ea-11ea-8c97-d7a46ada6e98.png)

I wrote out the flow-control as a pydot graph. There is clear duplication, multiple methods of resolving the Java location, multiple env vars, etc. More problematically, JAVA_HOME doesn't override all. 

I do think there is a case to refactor to:
(a) reduce duplication.
(b) Just calculate the Java location once, and pass into the appropriate functions.

We need to also build up a set of test conditions, e.g. with JRE instead of JDK.
