### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by woshizouguo** [kivy/pyjnius#598]
I am using the latest version:
I got this encoding error:

```
Traceback (most recent call last):
  File "<ipython-input-1-72f05b979b93>", line 1, in <module>
    self.parser.extract_single(pdf_path, jpage, jarea)
  File "jnius\jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius\jnius_export_class.pxi", line 939, in jnius.JavaMethod.call_method
  File "jnius\jnius_conversion.pxi", line 166, in jnius.convert_jobject_to_python
  File "jnius\jnius_conversion.pxi", line 234, in jnius.convert_jstring_to_python
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 2550686-2550687: illegal UTF-16 surrogate
```

In the java side, I use gson to convert Java object to json string. 

Do you have any idea how to avoid this issue?

**Comment by tshirtman** [comment]
Can you provide a simple way to reproduce the bug?

**Comment by Julian-O** [comment]
No reply after >12 months. Closing as can't repro
