### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by XY2323819551** [kivy/pyjnius#601]
Hi, I met the following issues when I am trying to run my code:
Traceback (most recent call last):
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py", line 22, in <module>
    from pyserini.search import SimpleSearcher, get_topics
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/search/__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, JDisjunctionMaxQueryGenerator, get_topics, get_topics_with_reader, get_qrels_file, get_qrels
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/search/_base.py", line 26, in <module>
    from ..pyclass import autoclass
  File "/home/zhangxy/QA/castorini/pyserini/pyserini/pyclass.py", line 30, in <module>
    from jnius import autoclass, cast
  File "/home/zhangxy/anaconda3/envs/pyserini2/lib/python3.6/site-packages/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/home/zhangxy/anaconda3/envs/pyserini2/lib/python3.6/site-packages/jnius/reflect.py", line 17, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/zhangxy/anaconda3/envs/pyserini2/lib/python3.6/site-packages/six.py", line 872, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 114, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 164, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 118, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 70, in jnius.create_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 47, in jnius.find_java_home
  File "/home/zhangxy/anaconda3/envs/pyserini2/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/zhangxy/anaconda3/envs/pyserini2/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.

And when i use "which java", system returned"
/home/zhangxy/condenv/java_env/jdk-11.0.2/bin/java"  also"which javac", returned"
/home/zhangxy/condenv/java_env/jdk-11.0.2/bin/javac"

what is wrong ?  I have spent two days on the issue……

**Comment by cmacdonald** [comment]
I think you can set the JAVA_HOME environment variable:
```python
import os
os.environ["JAVA_HOME"] = "/home/zhangxy/condenv/java_env/jdk-11.0.2"
```

at the start of your Python file. (or on the command line console before running the script)
