### ISSUE TITLE
test_jvm_options.py test failure

### ISSUE THREAD

**Issue by pgajdos** [kivy/pyjnius#617]
Hi,
for pythons 3.9 and 3.10 I get following test failure:

```
================================================================= FAILURES =================================================================
_____________________________________________________ TestJVMOptions.test_jvm_options ______________________________________________________

self = <test_jvm_options.TestJVMOptions object at 0x7f87e943d570>

    @pytest.mark.skipif(
        sys.platform == 'android',
        reason='JNIus on Android does not take JVM options'
    )
    def test_jvm_options(self):
        options = ['-Dtest.var{}=value'.format(i) for i in range(40)]
        process = subprocess.Popen(['python3', '-c', textwrap.dedent(
            '''\
            import jnius_config
            import json
            import sys
            jnius_config.set_options(*json.load(sys.stdin))
            import jnius
            ManagementFactory = jnius.autoclass("java.lang.management.ManagementFactory")
            json.dump(list(ManagementFactory.getRuntimeMXBean().getInputArguments()), sys.stdout)''')],
            bufsize=-1, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
        stdoutdata, _ = process.communicate(json.dumps(options).encode())
>       assert process.wait() == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <bound method Popen.wait of <Popen: returncode: 1 args: ['python3', '-c', 'import jnius_config\nimport j...>>()
E        +    where <bound method Popen.wait of <Popen: returncode: 1 args: ['python3', '-c', 'import jnius_config\nimport j...>> = <Popen: returncode: 1 args: ['python3', '-c', 'import jnius_config\nimport j...>.wait

tests/test_jvm_options.py:29: AssertionError
----------------------------------------------------------- Captured stderr call -----------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/abuild/rpmbuild/BUILDROOT/python-pyjnius-1.4.1-0.x86_64/usr/lib64/python3.10/site-packages/jnius/__init__.py", line 42, in <module>
    from .jnius import *  # noqa
ModuleNotFoundError: No module named 'jnius.jnius'
========================================================= short test summary info ==========================================================
FAILED tests/test_jvm_options.py::TestJVMOptions::test_jvm_options - AssertionError: assert 1 == 0
```
For 3.8, the test succeeds.

**Comment by misl6** [comment]
Hi @pgajdos ,
Seems that the issue has been fixed via https://github.com/kivy/pyjnius/pull/627/files

Feel free to re-open this issue if the test still fails for you.
