### ISSUE TITLE
Can autoclass convert a Groovy classs?

### ISSUE THREAD

**Issue by bnuzhouwei** [kivy/pyjnius#647]
Groovy is a multi-faceted language for the Java platform, can the autoclass convert a class of Groovy to python?

```python
gcl = autoclass('groovy.lang.GroovyClassLoader')()
clazz = gcl.parseClass('class Foo { void doIt() { println "ok" } }')
o = clazz.newInstance() 
o.doIt()
```

got error:

```error
Python.Runtime.PythonException: JVM exception occurred: startup failed:
General error during instruction selection: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject

java.lang.RuntimeException: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:977)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:672)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:636)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
Caused by: java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at groovy.lang.GroovyClassLoader.access$400(GroovyClassLoader.java:90)
	at groovy.lang.GroovyClassLoader$ClassCollector.createClass(GroovyClassLoader.java:700)
	at groovy.lang.GroovyClassLoader$ClassCollector.onClassNode(GroovyClassLoader.java:717)
	at groovy.lang.GroovyClassLoader$ClassCollector.call(GroovyClassLoader.java:721)
	at org.codehaus.groovy.control.CompilationUnit$3.lambda$call$0(CompilationUnit.java:807)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.codehaus.groovy.control.CompilationUnit$3.call(CompilationUnit.java:807)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:943)
	... 10 more
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:869)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:979)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:967)
	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:607)
	... 21 more
```

**Comment by cmacdonald** [comment]
I think you just need to have Groovy on the classpath ?
