### ISSUE TITLE
unexpected error for jdk17

### ISSUE THREAD

**Issue by di1l0o** [kivy/pyjnius#666]
```
(py2) xinglin@dell-Precision-7920-Tower:/8T/xinglin/projects/vectorize/src$  cd /8T/xinglin/projects/vectorize/src ; /usr/bin/env /home/xinglin/anaconda3/envs/py2/bin/python /home/xinglin/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/launcher 34833 -- /8T/xinglin/projects/vectorize/src/run_census.py 
Traceback (most recent call last):
  File "/8T/xinglin/projects/vectorize/src/run_census.py", line 1, in <module>
    import priv_sql_kernel
  File "/8T/xinglin/projects/vectorize/src/priv_sql_kernel.py", line 11, in <module>
    import elastic_sensitivity
  File "/8T/xinglin/projects/vectorize/src/elastic_sensitivity.py", line 15, in <module>
    es_vanilla = ES_Factory.load_vanilla()
  File "/8T/xinglin/projects/vectorize/src/es/es_util.py", line 37, in load_vanilla
    return ES_Factory.load('uber')
  File "/8T/xinglin/projects/vectorize/src/es/es_util.py", line 45, in load
    import jnius
  File "/home/xinglin/anaconda3/envs/py2/lib/python2.7/site-packages/jnius/__init__.py", line 13, in <module>
    from .reflect import *  # noqa
  File "/home/xinglin/anaconda3/envs/py2/lib/python2.7/site-packages/jnius/reflect.py", line 14, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/xinglin/anaconda3/envs/py2/lib/python2.7/site-packages/six.py", line 872, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 43, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 65, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 90, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 59, in jnius.create_jnienv
SystemError: Error calling dlopen(/home/xinglin/jdk-17.0.8/jre/lib/amd64/server/libjvm.so: /home/xinglin/jdk-17.0.8/jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory
(py2) xinglin@dell-Precision-7920-Tower:/8T/xinglin/projects/vectorize/src$ java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
(py2) xinglin@dell-Precision-7920-Tower:/8T/xinglin/projects/vectorize/src$ echo $JAVA_HOME
/home/xinglin/jdk-17.0.8/
```

**Comment by cmacdonald** [comment]
Can you show us the location of the .so files under
/home/xinglin/jdk-17.0.8/jre/lib/*/server/

Craig

**Comment by cmacdonald** [comment]
any news?

**Comment by cmacdonald** [comment]
pinging @di1l0o

**Comment by misl6** [comment]
Closing due to inactivity from the original author.

Please upgrade to `1.6.0` and open a new issue if the issue persists on your side.
