### ISSUE TITLE
JVM exception: Verifier rejected class … Constructor returning without calling superclass constructor 

### ISSUE THREAD

**Issue by eMPee584** [kivy/pyjnius#731]
Trying to build a kivymd GUI for the [DJI drone MSDK](https://developer.dji.com/mobile-sdk/) but not able to register the app with the framework because of following error. Can the verfifier be verriden, or any other idea?

```
 jnius.jnius.JavaException: Unable to found the constructor for dji/v5/manager/SDKManager

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/standard_nutzer/Downloads/SAMPLE-KIVYMD-APP/.buildozer/android/app/main.py", line 38, in <module>
   File "jnius/jnius_export_class.pxi", line 269, in jnius.jnius.JavaClass.__init__
   File "jnius/jnius_export_class.pxi", line 394, in jnius.jnius.JavaClass.call_constructor
   File "jnius/jnius_utils.pxi", line 79, in jnius.jnius.check_exception
 jnius.jnius.JavaException: JVM exception occurred: Verifier rejected class dji.v5.manager.SDKManager: void dji.v5.manager.SDKManager.<init>() failed to verify: void dji.v5.manager.SDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor
  void dji.v5.manager.SDKManager.<init>(dji.v5.manager.SDKManager$1) failed to verify: void dji.v5.manager.SDKManager.<init>(dji.v5.manager.SDKManager$1): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.v5.manager.SDKManager' appears in /data/app/com.dji.samplev5.aircraft-eAspws0ttIJMq9xY3EJ_Cw==/base.apk) java.lang.VerifyError
Python for android ended.
```

**Comment by kuzeyron** [comment]
If this is still an issue, please provide with more information that we can follow.
